import user from './user'
import root from './root'
import inventory from './inventory'
import category from './category'
import item from './item'
import debt from './debt'
import bill from './bill'
import task from './task'
import taskList from './taskList'
import houseMember from './houseMember'
import house from './house'
import appliance from './appliance'
import schedule from './schedule'
export default [root,user,inventory,item,category,debt,bill, task, taskList, houseMember, house, appliance, schedule]